# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_admin_dialog(object):
    def setupUi(self, admin_dialog):
        admin_dialog.setObjectName("admin_dialog")
        admin_dialog.resize(750, 617)
        admin_dialog.setMinimumSize(QtCore.QSize(750, 617))
        admin_dialog.setMaximumSize(QtCore.QSize(750, 617))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/app-logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        admin_dialog.setWindowIcon(icon)
        self.background_img_label = QtWidgets.QLabel(admin_dialog)
        self.background_img_label.setGeometry(QtCore.QRect(-140, -30, 1041, 661))
        self.background_img_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.background_img_label.setText("")
        self.background_img_label.setPixmap(QtGui.QPixmap("../images/background users.jpg"))
        self.background_img_label.setObjectName("background_img_label")
        self.admin_frame = QtWidgets.QFrame(admin_dialog)
        self.admin_frame.setGeometry(QtCore.QRect(150, 80, 450, 511))
        self.admin_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.admin_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.admin_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.admin_frame.setObjectName("admin_frame")
        self.list_label = QtWidgets.QLabel(self.admin_frame)
        self.list_label.setGeometry(QtCore.QRect(40, 40, 370, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.list_label.setFont(font)
        self.list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.list_label.setObjectName("list_label")
        self.taxi_listWidget = QtWidgets.QListWidget(self.admin_frame)
        self.taxi_listWidget.setGeometry(QtCore.QRect(40, 120, 370, 220))
        self.taxi_listWidget.setObjectName("taxi_listWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.admin_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 350, 371, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_status = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_status.setObjectName("frame_status")
        self.label_status_response = QtWidgets.QLabel(self.frame_status)
        self.label_status_response.setGeometry(QtCore.QRect(60, 0, 310, 30))
        self.label_status_response.setText("")
        self.label_status_response.setObjectName("label_status_response")
        self.label_status = QtWidgets.QLabel(self.frame_status)
        self.label_status.setGeometry(QtCore.QRect(0, 0, 60, 30))
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.frame_status)
        self.frame_location = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_location.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_location.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_location.setObjectName("frame_location")
        self.label_location_response = QtWidgets.QLabel(self.frame_location)
        self.label_location_response.setGeometry(QtCore.QRect(60, 0, 310, 30))
        self.label_location_response.setText("")
        self.label_location_response.setObjectName("label_location_response")
        self.label_location = QtWidgets.QLabel(self.frame_location)
        self.label_location.setGeometry(QtCore.QRect(0, 0, 60, 30))
        self.label_location.setObjectName("label_location")
        self.verticalLayout.addWidget(self.frame_location)
        self.frame_destination = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_destination.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_destination.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_destination.setObjectName("frame_destination")
        self.label_destination_response = QtWidgets.QLabel(self.frame_destination)
        self.label_destination_response.setGeometry(QtCore.QRect(60, 0, 310, 30))
        self.label_destination_response.setText("")
        self.label_destination_response.setObjectName("label_destination_response")
        self.label_destination = QtWidgets.QLabel(self.frame_destination)
        self.label_destination.setGeometry(QtCore.QRect(0, 0, 60, 30))
        self.label_destination.setObjectName("label_destination")
        self.verticalLayout.addWidget(self.frame_destination)
        self.download_button = QtWidgets.QPushButton(self.admin_frame)
        self.download_button.setGeometry(QtCore.QRect(155, 460, 141, 34))
        self.download_button.setObjectName("download_button")

        self.retranslateUi(admin_dialog)
        QtCore.QMetaObject.connectSlotsByName(admin_dialog)

    def retranslateUi(self, admin_dialog):
        _translate = QtCore.QCoreApplication.translate
        admin_dialog.setWindowTitle(_translate("admin_dialog", "Admin Access"))
        self.list_label.setText(_translate("admin_dialog", "Taxies "))
        self.label_status.setText(_translate("admin_dialog", "Estado"))
        self.label_location.setText(_translate("admin_dialog", "Ubicacion"))
        self.label_destination.setText(_translate("admin_dialog", "Destino"))
        self.download_button.setText(_translate("admin_dialog", "Download history"))

