# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'users.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_users_dialog(object):
    def setupUi(self, users_dialog):
        users_dialog.setObjectName("users_dialog")
        users_dialog.resize(986, 628)
        users_dialog.setMinimumSize(QtCore.QSize(986, 628))
        users_dialog.setMaximumSize(QtCore.QSize(986, 628))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/app-logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        users_dialog.setWindowIcon(icon)
        self.request_frame = QtWidgets.QFrame(users_dialog)
        self.request_frame.setGeometry(QtCore.QRect(250, 70, 451, 471))
        self.request_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.request_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.request_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.request_frame.setObjectName("request_frame")
        self.request_label = QtWidgets.QLabel(self.request_frame)
        self.request_label.setGeometry(QtCore.QRect(10, 40, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.request_label.setFont(font)
        self.request_label.setAlignment(QtCore.Qt.AlignCenter)
        self.request_label.setObjectName("request_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.request_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 140, 311, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.username_label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(44)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.username_label_12.sizePolicy().hasHeightForWidth())
        self.username_label_12.setSizePolicy(sizePolicy)
        self.username_label_12.setMinimumSize(QtCore.QSize(80, 0))
        self.username_label_12.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_label_12.setFont(font)
        self.username_label_12.setWordWrap(False)
        self.username_label_12.setObjectName("username_label_12")
        self.horizontalLayout_9.addWidget(self.username_label_12)
        self.origin_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.origin_lineEdit.setObjectName("origin_lineEdit")
        self.horizontalLayout_9.addWidget(self.origin_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.username_label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(44)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.username_label_13.sizePolicy().hasHeightForWidth())
        self.username_label_13.setSizePolicy(sizePolicy)
        self.username_label_13.setMinimumSize(QtCore.QSize(80, 0))
        self.username_label_13.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_label_13.setFont(font)
        self.username_label_13.setObjectName("username_label_13")
        self.horizontalLayout_5.addWidget(self.username_label_13)
        self.destination_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.destination_lineEdit.setObjectName("destination_lineEdit")
        self.horizontalLayout_5.addWidget(self.destination_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.username_label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(44)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.username_label_14.sizePolicy().hasHeightForWidth())
        self.username_label_14.setSizePolicy(sizePolicy)
        self.username_label_14.setMinimumSize(QtCore.QSize(80, 0))
        self.username_label_14.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_label_14.setFont(font)
        self.username_label_14.setObjectName("username_label_14")
        self.horizontalLayout_6.addWidget(self.username_label_14)
        self.date_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.date_lineEdit.setObjectName("date_lineEdit")
        self.horizontalLayout_6.addWidget(self.date_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.username_label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(44)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.username_label_15.sizePolicy().hasHeightForWidth())
        self.username_label_15.setSizePolicy(sizePolicy)
        self.username_label_15.setMinimumSize(QtCore.QSize(80, 0))
        self.username_label_15.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_label_15.setFont(font)
        self.username_label_15.setObjectName("username_label_15")
        self.horizontalLayout_4.addWidget(self.username_label_15)
        self.time_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.time_lineEdit.setObjectName("time_lineEdit")
        self.horizontalLayout_4.addWidget(self.time_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.request_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.request_button.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.request_button.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.request_button.setFont(font)
        self.request_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.request_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.request_button.setStyleSheet("")
        self.request_button.setIconSize(QtCore.QSize(20, 25))
        self.request_button.setCheckable(False)
        self.request_button.setObjectName("request_button")
        self.verticalLayout.addWidget(self.request_button)
        self.background_img_label = QtWidgets.QLabel(users_dialog)
        self.background_img_label.setGeometry(QtCore.QRect(0, 0, 991, 631))
        self.background_img_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.background_img_label.setText("")
        self.background_img_label.setPixmap(QtGui.QPixmap("../images/background users.jpg"))
        self.background_img_label.setObjectName("background_img_label")
        self.background_img_label.raise_()
        self.request_frame.raise_()

        self.retranslateUi(users_dialog)
        QtCore.QMetaObject.connectSlotsByName(users_dialog)

    def retranslateUi(self, users_dialog):
        _translate = QtCore.QCoreApplication.translate
        users_dialog.setWindowTitle(_translate("users_dialog", "Request a taxi"))
        self.request_label.setText(_translate("users_dialog", "Request a taxi"))
        self.username_label_12.setText(_translate("users_dialog", "Origin"))
        self.origin_lineEdit.setPlaceholderText(_translate("users_dialog", "Please enter the beginning"))
        self.username_label_13.setText(_translate("users_dialog", "Destination"))
        self.destination_lineEdit.setPlaceholderText(_translate("users_dialog", "Please enter the destination"))
        self.username_label_14.setText(_translate("users_dialog", "Date"))
        self.date_lineEdit.setPlaceholderText(_translate("users_dialog", "Please enter the estimated date"))
        self.username_label_15.setText(_translate("users_dialog", "Time"))
        self.time_lineEdit.setPlaceholderText(_translate("users_dialog", "Please enter the aproximate time"))
        self.request_button.setText(_translate("users_dialog", "Request"))

